"""전 세계 주요 기종 카탈로그 생성 (unlock_hours, purchase_price 포함)"""
import json
import os

DATA_PATH = os.path.join(os.path.dirname(__file__), 'data', 'aircraft.json')

# tier: 0=스타터, 1~7=해금 단계
TIERS = {
    0: {'unlock_hours': 0, 'purchase_price': 0},
    1: {'unlock_hours': 8, 'purchase_price': 2_500_000},
    2: {'unlock_hours': 20, 'purchase_price': 5_000_000},
    3: {'unlock_hours': 35, 'purchase_price': 10_000_000},
    4: {'unlock_hours': 55, 'purchase_price': 18_000_000},
    5: {'unlock_hours': 80, 'purchase_price': 30_000_000},
    6: {'unlock_hours': 120, 'purchase_price': 50_000_000},
    7: {'unlock_hours': 200, 'purchase_price': 80_000_000},
    8: {'unlock_hours': 350, 'purchase_price': 120_000_000},
}

CATALOG = [
    # ── 스타터 (무료) ──
    {'id': 'b737', 'name': 'Boeing 737-800', 'type': '소형 (Narrow-body)', 'category': '소형', 'tier': 0,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'CFM56-7B × 2', 'range_km': 5436, 'typical_pax': '189',
     'desc': '전 세계에서 가장 많이 운용되는 협동체. 신규 파일럿의 첫 기종.'},
    {'id': 'a320', 'name': 'Airbus A320-200', 'type': '소형 (Narrow-body)', 'category': '소형', 'tier': 0,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'CFM56 / V2500 × 2', 'range_km': 6100, 'typical_pax': '180',
     'desc': '플라이-바이-와이어 혁신 기종. 아시아나·제주항공 주력.'},

    # ── 소형/협동체 ──
    {'id': 'a321', 'name': 'Airbus A321-200', 'type': '소형', 'category': '소형', 'tier': 1,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'CFM56 × 2', 'range_km': 5950, 'typical_pax': '220',
     'desc': 'A320 패밀리 장형 버전. 대한항공 국내·일본 노선.'},
    {'id': 'b737max', 'name': 'Boeing 737 MAX 8', 'type': '소형', 'category': '소형', 'tier': 1,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'LEAP-1B × 2', 'range_km': 6570, 'typical_pax': '189',
     'desc': '737 차세대. 연료 효율 14% 향상.'},
    {'id': 'a320neo', 'name': 'Airbus A320neo', 'type': '소형', 'category': '소형', 'tier': 1,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'LEAP-1A / PW1100G × 2', 'range_km': 6300, 'typical_pax': '180',
     'desc': 'neo 엔진 탑재 A320. 연료 15% 절감.'},
    {'id': 'a220', 'name': 'Airbus A220-300', 'type': '소형', 'category': '소형', 'tier': 2,
     'manufacturer': 'Airbus', 'region': '캐나다', 'engine': 'PW1500G × 2', 'range_km': 6297, 'typical_pax': '160',
     'desc': '캐나다 Bombardier C Series 기반. 조용하고 효율적.'},
    {'id': 'e190', 'name': 'Embraer E190', 'type': '리저널', 'category': '리저널', 'tier': 2,
     'manufacturer': 'Embraer', 'region': '브라질', 'engine': 'CF34 × 2', 'range_km': 4537, 'typical_pax': '114',
     'desc': '브라질 엠브라에르 리저널 제트. 2-2 좌석 배열.'},
    {'id': 'e195', 'name': 'Embraer E195-E2', 'type': '리저널', 'category': '리저널', 'tier': 2,
     'manufacturer': 'Embraer', 'region': '브라질', 'engine': 'PW1900G × 2', 'range_km': 4815, 'typical_pax': '146',
     'desc': 'E2 세대 최대형. 아시아 LCC에서 증가 추세.'},
    {'id': 'b757', 'name': 'Boeing 757-200', 'type': '소형', 'category': '소형', 'tier': 3,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'RB211 × 2', 'range_km': 7220, 'typical_pax': '200',
     'desc': '고성능 협동체. 고고도 공항 이착륙 능력 탁월.'},
    {'id': 'md80', 'name': 'McDonnell Douglas MD-80', 'type': '소형', 'category': '클래식', 'tier': 2,
     'manufacturer': 'McDonnell Douglas', 'region': '미국', 'engine': 'JT8D × 2', 'range_km': 4260, 'typical_pax': '155',
     'desc': '후방 엔진 클래식 기종. 항공사 레트로 리버리 인기.'},
    {'id': 'tu154', 'name': 'Tupolev Tu-154', 'type': '소형', 'category': '클래식', 'tier': 3,
     'manufacturer': 'Tupolev', 'region': '러시아', 'engine': 'NK-8 × 3', 'range_km': 5280, 'typical_pax': '164',
     'desc': '소련 시대 3발 후방엔진기. 러시아·동유럽 전설.'},
    {'id': 'crj900', 'name': 'Bombardier CRJ-900', 'type': '리저널', 'category': '리저널', 'tier': 2,
     'manufacturer': 'Bombardier', 'region': '캐나다', 'engine': 'CF34 × 2', 'range_km': 2871, 'typical_pax': '90',
     'desc': '북미 지역선 주력. 컴팩트한 2-2 배열.'},
    {'id': 'a321neo', 'name': 'Airbus A321neo LR', 'type': '소형', 'category': '소형', 'tier': 3,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'LEAP-1A × 2', 'range_km': 7400, 'typical_pax': '220',
     'desc': '대서양 횡단 가능한 장거리 A321.'},

    # ── 중형 광동체 ──
    {'id': 'a330', 'name': 'Airbus A330-300', 'type': '중형 (Wide-body)', 'category': '중형', 'tier': 3,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'Trent 700 × 2', 'range_km': 10800, 'typical_pax': '300',
     'desc': '중장거리 광동체 대표. 대한항공·아시아나 유럽 노선.'},
    {'id': 'a330neo', 'name': 'Airbus A330-900neo', 'type': '중형', 'category': '중형', 'tier': 4,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'Trent 7000 × 2', 'range_km': 13334, 'typical_pax': '287',
     'desc': 'A330neo. 연료 효율 대폭 개선.'},
    {'id': 'b787', 'name': 'Boeing 787-9 Dreamliner', 'type': '중형', 'category': '중형', 'tier': 4,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GEnx × 2', 'range_km': 14100, 'typical_pax': '290',
     'desc': '복합소재 드림라이너. 승객 피로 감소 혁신.'},
    {'id': 'b78710', 'name': 'Boeing 787-10', 'type': '중형', 'category': '중형', 'tier': 5,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GEnx × 2', 'range_km': 11910, 'typical_pax': '330',
     'desc': '787 패밀리 최장형. 싱가포르항공 등 운용.'},
    {'id': 'a350', 'name': 'Airbus A350-900', 'type': '중형', 'category': '중형', 'tier': 5,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'Trent XWB × 2', 'range_km': 15000, 'typical_pax': '325',
     'desc': '탄소섬유 최신 광동체. 대한항공 주력 도입.'},
    {'id': 'a3501000', 'name': 'Airbus A350-1000', 'type': '중형', 'category': '중형', 'tier': 6,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'Trent XWB × 2', 'range_km': 14800, 'typical_pax': '366',
     'desc': 'A350 최대형. 카타르·영국항공 장거리.'},
    {'id': 'b767', 'name': 'Boeing 767-300ER', 'type': '중형', 'category': '중형', 'tier': 3,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'CF6 / PW4000 × 2', 'range_km': 11070, 'typical_pax': '269',
     'desc': '쌍발 광동체의 원조. 화물 전환도 많음.'},
    {'id': 'a340', 'name': 'Airbus A340-300', 'type': '중형', 'category': '클래식', 'tier': 4,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'CFM56-5C × 4', 'range_km': 13300, 'typical_pax': '295',
     'desc': '4발 광동체. ETOPS 제한 없는 장거리.'},
    {'id': 'a310', 'name': 'Airbus A310', 'type': '중형', 'category': '클래식', 'tier': 3,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'CF6 / PW4000 × 2', 'range_km': 8037, 'typical_pax': '220',
     'desc': 'A300 축소형. 유럽·중동 중거리 역사.'},
    {'id': 'dc10', 'name': 'McDonnell Douglas DC-10', 'type': '대형', 'category': '클래식', 'tier': 4,
     'manufacturer': 'McDonnell Douglas', 'region': '미국', 'engine': 'CF6 × 3', 'range_km': 9650, 'typical_pax': '270',
     'desc': '3발 광동체 레전드. 페덱스 화물로도 유명.'},
    {'id': 'il96', 'name': 'Ilyushin Il-96-300', 'type': '대형', 'category': '클래식', 'tier': 5,
     'manufacturer': 'Ilyushin', 'region': '러시아', 'engine': 'PS-90A × 4', 'range_km': 11500, 'typical_pax': '262',
     'desc': '러시아 대통령 전용기로도 유명한 4발기.'},

    # ── 대형 광동체 ──
    {'id': 'b777', 'name': 'Boeing 777-300ER', 'type': '대형', 'category': '대형', 'tier': 5,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GE90-115B × 2', 'range_km': 13649, 'typical_pax': '386',
     'desc': '쌍발 최대 여객기. 대한항공 미주·유럽 핵심.'},
    {'id': 'b777200', 'name': 'Boeing 777-200ER', 'type': '대형', 'category': '대형', 'tier': 4,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GE90 × 2', 'range_km': 14260, 'typical_pax': '313',
     'desc': '777 초기 장거리 모델.'},
    {'id': 'b777x', 'name': 'Boeing 777-9', 'type': '대형', 'category': '대형', 'tier': 6,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GE9X × 2', 'range_km': 13500, 'typical_pax': '426',
     'desc': '777X 차세대. 접이식 wingtip.'},
    {'id': 'b747', 'name': 'Boeing 747-8 Intercontinental', 'type': '대형', 'category': '대형', 'tier': 6,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GEnx-2B × 4', 'range_km': 14815, 'typical_pax': '467',
     'desc': '조종석이 위에 있는 전설의 여왕.'},
    {'id': 'a380', 'name': 'Airbus A380-800', 'type': '초대형', 'category': '대형', 'tier': 7,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'Trent 900 × 4', 'range_km': 14800, 'typical_pax': '555',
     'desc': '세계 유일 2층 초대형기. 대한항공도 운용.'},
    {'id': 'b747sp', 'name': 'Boeing 747SP', 'type': '대형', 'category': '클래식', 'tier': 5,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'JT9D × 4', 'range_km': 12450, 'typical_pax': '331',
     'desc': '747 축소 특별형. 희귀 클래식.'},
    {'id': 'md11', 'name': 'McDonnell Douglas MD-11', 'type': '대형', 'category': '클래식', 'tier': 4,
     'manufacturer': 'McDonnell Douglas', 'region': '미국', 'engine': 'CF6 × 3', 'range_km': 12670, 'typical_pax': '293',
     'desc': '3발 광동체. 화물기로도 전설.'},

    # ── 화물기 ──
    {'id': 'b777f', 'name': 'Boeing 777F', 'type': '화물기', 'category': '화물기', 'tier': 5,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GE90 × 2', 'range_km': 9200, 'typical_pax': '화물',
     'desc': '대한항공 카고 주력. 최대 100톤 적재.'},
    {'id': 'b747f', 'name': 'Boeing 747-8F', 'type': '화물기', 'category': '화물기', 'tier': 6,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'GEnx-2B × 4', 'range_km': 8130, 'typical_pax': '화물',
     'desc': '747 최종 화물 버전. 140톤 적재.'},
    {'id': 'a330f', 'name': 'Airbus A330-200F', 'type': '화물기', 'category': '화물기', 'tier': 4,
     'manufacturer': 'Airbus', 'region': '유럽', 'engine': 'Trent 700 × 2', 'range_km': 7400, 'typical_pax': '화물',
     'desc': 'A330 기반 중형 화물기.'},
    {'id': 'b767f', 'name': 'Boeing 767-300F', 'type': '화물기', 'category': '화물기', 'tier': 3,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'CF6 × 2', 'range_km': 6025, 'typical_pax': '화물',
     'desc': '아마존·UPS 등 이커머스 화물 주력.'},
    {'id': 'md11f', 'name': 'MD-11F', 'type': '화물기', 'category': '화물기', 'tier': 4,
     'manufacturer': 'McDonnell Douglas', 'region': '미국', 'engine': 'CF6 × 3', 'range_km': 7285, 'typical_pax': '화물',
     'desc': '페덱스 카고 전설의 기종.'},
    {'id': 'an124', 'name': 'Antonov An-124', 'type': '화물기', 'category': '화물기', 'tier': 7,
     'manufacturer': 'Antonov', 'region': '우크라이나', 'engine': 'D-18T × 4', 'range_km': 4800, 'typical_pax': '화물',
     'desc': '거대 전략수송기. 초대형 화물 전용.'},
    {'id': 'an225', 'name': 'Antonov An-225 Mriya', 'type': '화물기', 'category': '화물기', 'tier': 8,
     'manufacturer': 'Antonov', 'region': '우크라이나', 'engine': 'D-18T × 6', 'range_km': 15400, 'typical_pax': '화물',
     'desc': '세계 최대 항공기. 전설 중의 전설.'},

    # ── 터보프롭 / 리저널 ──
    {'id': 'atr72', 'name': 'ATR 72-600', 'type': '터보프롭', 'category': '리저널', 'tier': 1,
     'manufacturer': 'ATR', 'region': '프랑스/이탈리아', 'engine': 'PW127 × 2', 'range_km': 1528, 'typical_pax': '78',
     'desc': '프랑스-이탈리아 터보프롭. 제주·지역선.'},
    {'id': 'q400', 'name': 'De Havilland Dash 8 Q400', 'type': '터보프롭', 'category': '리저널', 'tier': 2,
     'manufacturer': 'De Havilland', 'region': '캐나다', 'engine': 'PW150A × 2', 'range_km': 2040, 'typical_pax': '90',
     'desc': '캐나다 터보프롭. 소음저감 프로펠러.'},
    {'id': 'e175', 'name': 'Embraer E175', 'type': '리저널', 'category': '리저널', 'tier': 2,
     'manufacturer': 'Embraer', 'region': '브라질', 'engine': 'CF34 × 2', 'range_km': 3334, 'typical_pax': '88',
     'desc': '북미 지역선 핵심 리저널 제트.'},
    {'id': 'saab340', 'name': 'Saab 340', 'type': '터보프롭', 'category': '리저널', 'tier': 1,
     'manufacturer': 'Saab', 'region': '스웨덴', 'engine': 'CT7 × 2', 'range_km': 1732, 'typical_pax': '36',
     'desc': '스웨덴 소형 터보프롭. 귀여운 프로펠러기.'},

    # ── 비즈니스/특수 ──
    {'id': 'g650', 'name': 'Gulfstream G650', 'type': '비즈니스', 'category': '비즈니스', 'tier': 5,
     'manufacturer': 'Gulfstream', 'region': '미국', 'engine': 'BR725 × 2', 'range_km': 13890, 'typical_pax': '19',
     'desc': '최고급 비즈니스 제트. 기장의 꿈.'},
    {'id': 'citation', 'name': 'Cessna Citation X', 'type': '비즈니스', 'category': '비즈니스', 'tier': 4,
     'manufacturer': 'Cessna', 'region': '미국', 'engine': 'AE3007 × 2', 'range_km': 6019, 'typical_pax': '12',
     'desc': '세스나 최고속 비즈니스 제트.'},
    {'id': 'falcon7x', 'name': 'Dassault Falcon 7X', 'type': '비즈니스', 'category': '비즈니스', 'tier': 5,
     'manufacturer': 'Dassault', 'region': '프랑스', 'engine': 'PW307A × 3', 'range_km': 10200, 'typical_pax': '16',
     'desc': '프랑스 다소 삼발 비즈니스 제트.'},
    {'id': 'c130', 'name': 'Lockheed C-130 Hercules', 'type': '군수', 'category': '특수', 'tier': 4,
     'manufacturer': 'Lockheed', 'region': '미국', 'engine': 'T56 × 4', 'range_km': 3800, 'typical_pax': '군수',
     'desc': '전 세계 공군 수송기의 상징.'},
    {'id': 'concorde', 'name': 'Concorde', 'type': '초음속', 'category': '클래식', 'tier': 8,
     'manufacturer': 'BAC/Aérospatiale', 'region': '영국/프랑스', 'engine': 'Olympus 593 × 4', 'range_km': 7223, 'typical_pax': '128',
     'desc': '유일한 초음속 여객기. 마하 2.04.'},
    {'id': 'b707', 'name': 'Boeing 707', 'type': '대형', 'category': '클래식', 'tier': 3,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'JT3D × 4', 'range_km': 9200, 'typical_pax': '189',
     'desc': '제트여객기 시대를 연 최초의 보잉 제트.'},
    {'id': 'comac919', 'name': 'COMAC C919', 'type': '소형', 'category': '소형', 'tier': 3,
     'manufacturer': 'COMAC', 'region': '중국', 'engine': 'LEAP-1C × 2', 'range_km': 5555, 'typical_pax': '168',
     'desc': '중국 최초 자체 개발 대형 여객기.'},
    {'id': 'ssj100', 'name': 'Sukhoi Superjet 100', 'type': '리저널', 'category': '리저널', 'tier': 2,
     'manufacturer': 'Sukhoi', 'region': '러시아', 'engine': 'SaM146 × 2', 'range_km': 3048, 'typical_pax': '98',
     'desc': '러시아 신형 리저널 제트.'},
    {'id': 'b29', 'name': 'Boeing B-29 Superfortress', 'type': '군수', 'category': '클래식', 'tier': 6,
     'manufacturer': 'Boeing', 'region': '미국', 'engine': 'R-3350 × 4', 'range_km': 5230, 'typical_pax': '역사',
     'desc': '제2차 대전 폭격기. 항공 역사 박물관.'},
]

ILLUSTRATIONS = {
    'b737': 'https://upload.wikimedia.org/wikipedia/commons/9/95/Boeing_737-800_v1.0.png',
    'a320': 'https://upload.wikimedia.org/wikipedia/commons/8/86/Airbus_A320_v1.0.png',
    'a321': 'https://upload.wikimedia.org/wikipedia/commons/8/81/Airbus_A321_v1.0.png',
    'a330': 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Airbus_A330-300_v1.0.png',
    'a350': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/A350_variant_sizes.svg/1280px-A350_variant_sizes.svg.png',
    'b777': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Boeing_777_family_v1.1.png',
    'b787': 'https://upload.wikimedia.org/wikipedia/commons/3/31/Boeing_787-800_Dreamliner_v1.0.png',
    'a380': 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Airbus_A380-800_v1.0.png',
    'b747f': 'https://upload.wikimedia.org/wikipedia/commons/8/85/Boeing_747_family_v1.0.png',
    'b757': 'https://upload.wikimedia.org/wikipedia/commons/5/58/Boeing_757_family_v1.0.png',
    'a340': 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Airbus_A340-300_v1.0.png',
    'b777f': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Boeing_777_family_v1.1.png',
    'b777200': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Boeing_777_family_v1.1.png',
}


def build_entry(ac):
    tier = ac.get('tier', 3)
    t = TIERS.get(tier, TIERS[3])
    base_id = ac['id']
    illust = ILLUSTRATIONS.get(base_id) or ILLUSTRATIONS.get(
        base_id.replace('neo', '').replace('max', '').replace('200', '').replace('f', '')[:4]
    )
    return {
        'id': ac['id'],
        'name': ac['name'],
        'type': ac['type'],
        'category': ac['category'],
        'manufacturer': ac.get('manufacturer', ''),
        'region': ac.get('region', ''),
        'tier': tier,
        'unlock_hours': t['unlock_hours'],
        'purchase_price': t['purchase_price'],
        'length_m': str(35 + tier * 2),
        'wingspan_m': str(30 + tier * 2),
        'height_m': str(11 + tier * 0.5),
        'mtow_kg': 70000 + tier * 30000,
        'oew_kg': 40000 + tier * 15000,
        'engine': ac.get('engine', '—'),
        'range_km': ac.get('range_km', 5000),
        'cruise_kmh': 820 + tier * 5,
        'typical_pax': ac.get('typical_pax', '—'),
        'fuel_burn': round(2.5 + tier * 0.8, 1),
        'illustration': illust or '',
        'desc': ac.get('desc', ''),
        'sellable': False,
    }


if __name__ == '__main__':
    result = [build_entry(ac) for ac in CATALOG]
    with open(DATA_PATH, 'w', encoding='utf-8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
    print(f'Generated {len(result)} aircraft types → {DATA_PATH}')